# The first comment of the game the legend of Kira
# Kira has to choose options to progress through the story and overcome challenges.

# print the character brothers
def skiraton():
    print("         .7")
    print("       .'/'")
    print("      / /")
    print("     / / ")
    print("   __|/")
    print(" ,-\__\\")
    print(" |f-\"Y\\|")
    print(" \\()7L/")
    print("  cgD                            __ _")
    print("  |\\(                          .'  Y '>,")
    print("   \\ \\                        / _   _   \\")
    print("    \\\\\\                       )(_) (_)(|})")
    print("     \\\\\\                      {  4A   } /")
    print("      \\\\\\                      \\uLuJJ/\\l")
    print("       \\\\\\                     |3    p)/")
    print("        \\\\___ __________      /nnm_n//")
    print("        c7___-__,__-)\\,__)('.  \\_>-<_/D")
    print("                   //V     \\_\"-._.__G G_c__.-__<\"/ ")
    print("                          <\"-._>__-,G_.___)\\   \\7\\")
    print("                         (\"-.__.| \\\"<.__.-\" )   \\ \\")
    print("                         |\"-.__\"\\  |\"-.__.-\".\\   \\ \\")
    print("                         (\"-.__\"\". \\\"-.__.-\".|    \\_\\")
    print("                         \\\"-.__\"\"|!|\"-.__.-\".)     \\ \\")
def lila():
    print("                    ,_  .--.")
    print("              , ,   _)\\/    ;--.")
    print("      . ' .    \\_\\-'   |  .'    \\")
    print("     -= * =-   (.-,   /  /       |")
    print("      ' .\\'    ).  ))/ .'   _/\\ /")
    print("          \\_   \\_  /( /     \\ /(")
    print("          /_\\ .--'   `-.    //  \\")
    print("          ||\\/        , '._//    |")
    print("          ||/ /`(_ (_,;`-._/     /")
    print("          \\_.'   )   /`\\       .'")
    print("               .' .  |  ;.   /`")
    print("              /      |\\(  `.( ")
    print("             |   |/  | `    `")
    print("             |   |  /")
    print("             |   |.'")
    print("          __/   /")
    print("      _ .'  _.-`")
    print("   _.` `.-;`")
    print("  /_.-'`")
def thorne():
    print("           .  .")
    print("           |\\_|\\")
    print("           | a_a\\")
    print("           | | \"]")
    print("       ____| '-\\___")
    print("      /.----.___.-'\\")
    print("     //        _    \\")
    print("    //   .-. (~v~) /|")
    print("   |'|  /\\:  .--  / \\")
    print("  // |-/  \\_/____/\\/~|")
    print("|/  \\ |  []_|_|_] \\ |")
    print("| \\  | \\ |___   _\\ ]_}")
    print("| |  '-' /   '.'  |")
    print("| |     /    /|:  | ")
    print("| |     |   / |:  /\\")
    print("| |     /  /  |  /  \\")
    print("| |    |  /  /  |    \\")
    print("\\ |    |/\\/  |/|/\\    \\")
    print(" \\|\\ |\\|  |  | / /\\/\\__\\")
    print("   \\ \\| | /   | |__")
    print("        / |   |____)")
    print("        |_/")
def zephyr():
    print("              .=.,")
    print("             ;c =\\")
    print("           __|  _/")
    print("         .'-'-._/-'-._")
    print("        /..   ____    \\")
    print("       /' _  [<_->] )  \\")
    print("      (  / \\--\\_>/-/'._ )")
    print("       \\-;/\\__;__/ _/ _/")
    print("        '._}|==o==\\{_\\/")
    print("         /  /-._.--\\  \\_")
    print("        // /   /|   \\ \\ \\")
    print("       / | |   | \\;  |  \\ \\")
    print("      / /  | :/   \\: \\   \\_\\")
    print("     /  |  /.'|   /: |    \\ \\")
    print("     |  |  |--| . |--|     \\_\\")
    print("     / _/   \\ | : | /___--._) \\")
    print("    |_(---'-| >-'-| |       '-'")
    print("           /_/     \\_\\")    

# character selection
def character_selection():
    decorative_lines = "-"*60
    print("Welcome to 'The Legend of Kira'!")
    print(decorative_lines)
    print("Select your character:")
    print("1. Skiraton - The Brave and Fearless Warrior")
    skiraton()
    print(decorative_lines)
    print("2. Lila - The Wise Fairy")
    lila()
    print(decorative_lines)
    print("3. Thorne - The Stealthy Rogue")
    thorne()
    print(decorative_lines) 
    print("4. Zephyr - The Swift Alien")
    zephyr()
    print(decorative_lines)
    choice = input("Enter the number of your choice: ")
    return choice

character_selection()